export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const TOGGLE_CART_DROPDOWN = "TOGGLE_CART_DROPDOWN";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_IN_CART = "REMOVE_ITEM_IN_CART";
export const CLEAR_ITEM_IN_CART = "CLEAR_ITEM_IN_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_SHOP = "UPDATE_SHOP";
